blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: https://aiblocks.stackexchange.com/questions/ask
    about: Please ask questions here
  - name: Developer mailing list
    url: https://groups.google.com/g/aiblocks-dev
    about: Discuss Core Advancement Proposals (CAPs) and AiBlocks Ecosystem Proposals (AEPs) and talk about development of aiblocks-core, Millennium, and the rest of the AiBlocks platform. A place for conversations that move the protocol and ecosystem forward.
  - name: Protocol requests
    url: https://github.com/aiblocks/aiblocks-protocol
    about: Propose changes to the AiBlocks protocol (AAPs) or ecosystem (SEPs) standards
